name: Green-Cart_CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    
jobs:
    ci:
        runs-on: ubuntu-latest

        steps: 
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build Application
              run: docker compose build

            - name: Start Application
              run: docker compose up -d

            - name: Check Containers
              run: docker compose ps

            - name: Check Container logs
              run: docker compose logs

            - name: Stop Application
              if: always()
              run: docker compose down
